- name: C++
  img: https://cdn.jsdelivr.net/gh/devicons/devicon/icons/cplusplus/cplusplus-original.svg
  content: <ul class="aboutme_badge_desc badge-left">
    <li>ㅡ <span class="HL">객체지향적 설계</span>에 따라 개발할 수 있습니다.</li>
    <li>ㅡ DirectX 11, IMGUI을 사용하여 그래픽 프로그래밍을 할 수 있습니다.</li>
    <li>ㅡ Neural Network, Pagerank 등을 C++을 사용하여 구현할 수 있습니다.</li>
    </ul>

- name: Pytorch
  img: https://cdn.jsdelivr.net/gh/devicons/devicon/icons/pytorch/pytorch-original.svg
  content: <ul class="aboutme_badge_desc badge-left2">
    <li>ㅡ ML / DL 논문의 내용을 바탕으로 <span class="HL">모델 구현</span>을 할 수 있습니다.</li>
    <li>ㅡ <a style="color:yellow" href="https://github.com/charlieppark/ML_Papers_Implementation/tree/main">https://github.com/charlieppark/ML_Papers_Implementation/tree/main</a></li>
    <li>ㅡ DGL 라이브러리를 사용하여 GCN을 다룰 수 있습니다.</li>
    </ul>

- name: Numpy
  img: https://cdn.jsdelivr.net/gh/devicons/devicon/icons/numpy/numpy-original.svg
  content: <ul class="aboutme_badge_desc badge-center1">
    <li>ㅡ Backpropagation을 포함하여 <span class="HL">Neural Network</span>를 구현할 수 있습니다.</li>
    <li>ㅡ 데이터 전처리 및 feature extraction을 수행할 수 있습니다.</li>
    </ul>

- name: Google JAX
  img: https://raw.githubusercontent.com/google/jax/main/images/jax_logo_250px.png
  content: <ul class="aboutme_badge_desc badge-center2">
    <li>ㅡ 기본 튜토리얼을 모두 학습하였으며, 기초적인 연산을 사용할 수 있습니다.</li>
    <li>ㅡ Google JAX 기반으로 Neural Network를 구현 및 학습할 수 있습니다.</li>
    </ul>

- name: Flutter
  img: https://cdn.jsdelivr.net/gh/devicons/devicon/icons/flutter/flutter-original.svg
  content: <ul class="aboutme_badge_desc badge-right2">
    <li>ㅡ Frontend Design을 바탕으로 UI를 구현할 수 있습니다.</li>
    <li>ㅡ HTTP API 바탕의 통신을 수행할 수 있습니다.</li>
    </ul>

- name: Spring Boot
  img: https://cdn.jsdelivr.net/gh/devicons/devicon/icons/spring/spring-original.svg
  content: <ul class="aboutme_badge_desc badge-right2">
    <li>ㅡ HTTP API 기반의 웹 서버를 구현할 수 있습니다.</li>
    <li>ㅡ Layered Architecture를 사용하여, 의존적이지 않으며 안정적인 구조를 설계할 수 있습니다.</li>
    <li>ㅡ Lombok, MapStruct, JPA Repository 등을 사용하여, 개발자의 실수를 줄이는 구현을 수행할 수 있습니다.</li>
    </ul>

- name: Github
  img: https://cdn.jsdelivr.net/gh/devicons/devicon/icons/github/github-original.svg
  content: <ul class="aboutme_badge_desc badge-right2">
    <li> Github 등급 ( API ： <span id="git_state" style="color:yellow; cursor:pointer;">Github Readme Stats</span> )</li>
    <img src = "https://github-readme-stats.vercel.app/api?username=charlieppark&amp;count_private=true&amp;hide=contribs,prs&amp;show_icons=true&amp;theme=vue-dark" id="my_git_state" style ="cursor:pointer;">
    <script>
    git_state = document.getElementById('git_state');
    git_state.addEventListener('click', () => {
    location.href="https://github.com/anuraghazra/github-readme-stats";
    });

    my_git_state = document.getElementById('my_git_state');
    my_git_state.addEventListener('click', () => {
    location.href="https://github.com/charlieppark";
    });
    </script>
    </ul>

- name: Git
  img: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/git/git-original.svg"
  content: <ul class="aboutme_badge_desc badge-right">
    <li>ㅡ Git을 사용하여 버전 관리 및 협업을 진행할 수 있습니다.</li>
    <li>ㅡ Git Hook, Github Action 등을 사용하여, 버전관리와 CI/CD의 연동을 수행할 수 있습니다.</li>
    <li>ㅡ Git Flow, Commit Message Convention, Github Project와 Issue를 통한 관리를 사용해 생산적인 협업을 주도할 수 있습니다.</li>
    </ul>
